### ISSUE TITLE
Segmentation fault with simple stimulus example

### ISSUE THREAD

**Issue by halfflat** [BlueBrain/CoreNeuron#159]
Granting that this might be user error, the python script below crashes with a segmentation fault. No output files are generated.

System info and versions:
* System is GNU/Linux (Artix)
* `nrniv --version` reports `NEURON -- VERSION 7.6.2-2-gd3ead4a+ unknown (d3ead4a+) 2018-08-24`
* CoreNEURON is at 0.14 tag.
* Python is 3.7.2

```
#!/usr/bin/env python

from neuron import h

class soma_cell:
    def __init__(self):
        self.soma = h.Section(name='soma')
        self.soma.diam = 20
        self.soma.L = 20

        self.syn  = h.ExpSyn(self.soma(0.5))

h('load_file("stdrun.hoc")')
h.cvode.cache_efficient(1)
pc = h.ParallelContext()

cell = soma_cell()
stim = h.NetStim()
stim.number = 1
stim.start = 0

g0 = 0.1 # [µS]
nc_stim = h.NetCon(stim, cell.syn, 0, 0, g0, sec=cell.soma)

h.dt = 0.025
pc.set_maxstep(1)
pc.nrnbbcore_write("cnrn")
```

**Comment by nrnhines** [comment]
There are three requirements that are missing. It can be considered a bug
that when these requirements are missing, that a descriptive error is
not generated. Or some of the requirements can be removed.

First, one must initialize the model before calling nrnbbcore_write.
In your case this can be accomplished by
h.finitialize(-65)

Second, after fixing the above you would get
python3: ../../../nrn/src/nrniv/nrnbbcore_write.cpp:1357:
void write_nrnthread(const char*, NrnThread&, nrncore_CellGroup&):
Assertion `cg.group_id >= 0' failed.

i.e, to write files at least one of the cells has to be associated with
a global identifier. In your case this can be accomplished with
pc.set_gid2node(0, 0)
pc.cell(0, h.NetCon(cell.soma(.5)._ref_v, None))

Third, the folder where the files are to be written must exist.
Otherwise you see:
NEURON: nrnbbcore_write write_byteswap1 could not open for writing: %s
 cnrn/byteswap1.dat

**Comment by halfflat** [comment]
Thanks for the quick reply and fixes!

In what other ways can a model be initalized for the purposes of `nrnbbcore_write()`? I see that the ringtest demo uses `h.stdinit()`, which I presume calls the hoc `stdinit` proc from `stdrun.hoc`, and that this ultimately also calls `finitialize()`. Are there other API interfaces for this?

**Comment by nrnhines** [comment]
No others of note. I guess I recommend h.stdinit() as it is GUI aware.

**Comment by halfflat** [comment]
Thanks for the info.

In terms of improving the user experience, it would indeed be helpful if NEURON could catch these errors and report them.

**Comment by nrnhines** [comment]
nrnsimulator/nrn changset 4509a11b967 generates more informative error messages. At some point
the requirement that each thread has a real cell with a gid needs to be eliminated.
