### ISSUE TITLE
If mod file is not used, continue simulation (even if mod file is different between neuron and coreneuron)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#54]
Currently even if mod file is not used, we get error like:

{code}
○ → srun -n 32 $CORENEURON_EXEC -mpi -d $BLUECONFIG_OUTPUT_ROOT/data -o $BLUECONFIG_OUTPUT_ROOT/data -e $BLUECONFIG_DURATION -dt $BLUECONFIG_DT -k $BLUECONFIG_FORWARD_SKIP -r 1 -w $BLUECONFIG_DT_REPORT -R 0
 num_mpi=32
 num_omp_thread=64

 Memory (MBs) :            After MPI_Init : Max 10.0977, Min 10.0352, Avg 10.0371
Info: No default arguments file provided: config
hh prop sizes differ psize 25 19   dpsize 6 6
hh prop sizes differ psize 25 19   dpsize 6 6
hh prop sizes differ psize 25 19   dpsize 6 6
hh prop sizes differ psize 25 19   dpsize 6 6
{code}

We should just print the warning and continue simulation.

**Comment by nrnhines** [comment]
I believe the best way to implement this enhancement is to create an integer set of mechanism types that cannot be used. This can be done by inserting the offending mechanism type into the set instead of
printing the above error message.  Then in the nrn_setup.cpp loop beginning in line 988 when
a used type is read at line 995, just check to see if the type is in the set and, if so, print an error message
(will want to exit when the loop completes).

**Comment by nrnhines** [comment]
To avoid multiple error messaes from different threads and ranks, may want to create a union set of
all the mechanisms that are used that cannot be used.

**Comment by pramodk** [comment]
Ok, I will implement this as per above suggestion.

**Comment by nrnhines** [comment]
Although a set seems most elegant, perhaps a integer vector of length n_memb_mech would be
most direct when one gets to the point of giving rang 0 thread 0 enough information to print
the error messages from a MPI_Allreduce using max.  Any element with a value > 2 means that someone
is using the mechanism. Elements become > 2 because they start out at 1 if the are not supposed to
be used, and then if > 0 change to 2 if used.
