### ISSUE TITLE
mismatch in number of compartments between NEURON and CoreNeuron

### ISSUE THREAD

**Issue by sharkovsky** [BlueBrain/CoreNeuron#60]
Creating a dataset consisting of a single cell, I noticed that the number of compartments that I count in NEURON and those reported by CoreNeuron are different.

To replicate this (assumes you have `nrnivmodl` and `coreneuron_exec` in your path):
```bash
$ git clone git@github.com:sharkovsky/NEURON_VS_CoreNeruon_mismatch.git
$ cd NEURON_VS_CoreNeruon_mismatch
$ nrnivmodl L5_TTPC1_cADpyr232_1/mechanisms/
$ ./x86_64/special -python singlecell.py
```
The output of this command should be:
```bash
Before calling geom_nseg
tot nsec: 239 tot nseg: 239
After calling geom_nseg
tot nsec: 239 tot nseg: 913
```
As you can see, the number of compartments counted is `913`.

Now run coreneuron and get the output
```bash
$ coreneuron_exec -d coredat/single_cell -e 1
 Simulation Statistics
 Number of cells: 1
 Number of compartments: 1153
 Number of presyns: 1
 Number of input presyns: 0
```

Here, the reported number of compartments is `1153`.

For reproducibility, I am using BlueBrain/CoreNeuron@12effbf03f69a9b65ce8aace5a4bd62114d07076 and nrnhines/nrn@e9b2bb1a7b6faf5664d

Thank you

**Comment by nrnhines** [comment]
NEURON is reporting the number of zon-zero area segments (sum of nseg over all sections).
Coreneuron includes the zero-area segments (one more that the number of sections because it is a tree) in its total.
913+ 239 + 1 = 1153. Generally speaking (absence of synapses at locations 0 and 1 of a section) there is minimal computational effort involved in setting up the algebraic equation (not ODE)  for the
zero area nodes and the extra effort for gaussian elimination is annoying but not too bad. Zero area compartments at the ends of sections (shared when connected to other sections) helps with second
order spatial correctness under conditions of current stimulation and branching.

**Comment by nrnhines** [comment]
I don't know if changing the statistic label to "number of nodes" or "rank of the current balance matrix"
would be worthwhile.

**Comment by sharkovsky** [comment]
Thank you Michael!

**Comment by pkuzyc** [comment]
I tried to use the current commit of CoreNEURON to simulate this PC model, but there is a segmentation fault when I run it. The same error also happens when I run ringtest with this commit.  The error message is :  
```
--- Copying to Device! ---
-----------COPYING 0'th NrnThread TO DEVICE ---------------
GPU MEMORY USAGE (MB) : Used = 66.375000, Free = 11373.500000 MB, Total = 11439.875000zsh: segmentation fault (core dumped)  ./coreneuron_exec -e 100 -d  --gpu
```
is there anything wrong?

**Comment by nrnhines** [comment]
Something is wrong but I don't know if the problem is a coreneuron bug, limitation, or a small change
to the model is requjired. If the model fits into a reasonable size zip file, you can send that to me and
I will look into the issue. Send to michael.hines@yale.edu

**Comment by pramodk** [comment]
Hi Michael, Yichen,

I am able to reproduce the issue with ring test and it seems like this is a bug introduced in last few months. I created separate issue #61 to track this.

**Comment by pramodk** [comment]
@pkuzyc : #62 should fix the issue. I tested simple ring test as:

```
$ cd CoreNeuron/build
$ ./bin/coreneuron_exec -e 100 -d ../tests/integration/ring/ --gpu
```
